version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build-prod

artifacts:
  files:
    - '**/*'
  base-directory: 'dist/culture-dashboard-portal'

cache:
  paths:
    - 'node_modules/**/*'
